"use client";

import { buttonClasses } from "@/components/ui/button";
import { motion } from "framer-motion";
import { ArrowRight, BadgeCheck, Camera, FileText, Languages, MessageCircle, Upload } from "lucide-react";
import Image from "next/image";
import Link from "next/link";

const heroImage =
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1400&q=80";

const generatedTags = [
  { icon: FileText, label: "Exposé written" },
  { icon: Languages, label: "6 languages" },
  { icon: MessageCircle, label: "AI agent live" },
  { icon: BadgeCheck, label: "FAQ generated" },
];

export function Hero() {
  return (
    <section className="container-page grid items-center gap-12 py-16 md:py-20 lg:grid-cols-[1.05fr_0.95fr]">
      <div>
        <motion.p
          className="eyebrow"
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          Verified marketplace · Spain first
        </motion.p>
        <motion.h1
          className="mt-4 text-4xl leading-[1.08] font-semibold text-navy-950 sm:text-5xl"
          initial={{ opacity: 0, y: 14 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.05 }}
        >
          Professional property marketing. Powered by AI.
        </motion.h1>
        <motion.p
          className="mt-5 max-w-lg text-lg leading-relaxed text-navy-600"
          initial={{ opacity: 0, y: 14 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.12 }}
        >
          Upload photos. Zouza creates the listing — exposé, FAQ, six
          translations, and a dedicated AI assistant that answers enquiries
          around the clock.
        </motion.p>
        <motion.div
          className="mt-8 flex flex-wrap items-center gap-3"
          initial={{ opacity: 0, y: 14 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          <Link href="/create-listing" className={buttonClasses("primary", "lg")}>
            <Upload className="h-4.5 w-4.5" aria-hidden />
            Upload photos
          </Link>
          <Link href="/rent" className={buttonClasses("outline", "lg")}>
            Explore homes
            <ArrowRight className="h-4 w-4" aria-hidden />
          </Link>
        </motion.div>
        <motion.p
          className="mt-6 text-sm text-navy-500"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.3 }}
        >
          Free to try · No agency contract · Every cost shown upfront
        </motion.p>
      </div>

      {/* Product panel — the generated listing, as a receipt */}
      <motion.div
        className="mx-auto w-full max-w-md rounded-xl border border-line bg-white p-1.5 shadow-card"
        initial={{ opacity: 0, y: 24 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.7, delay: 0.15 }}
      >
        <div className="relative aspect-[16/10] overflow-hidden rounded-lg bg-sand">
          <Image
            src={heroImage}
            alt="A whitewashed Mediterranean villa with a pool, presented as a Zouza listing"
            fill
            priority
            sizes="(max-width: 1024px) 100vw, 40vw"
            className="object-cover"
          />
          <span className="absolute top-3 left-3 inline-flex items-center gap-1.5 rounded-lg bg-navy-950/85 px-3 py-1 text-xs font-medium text-ivory backdrop-blur">
            <Camera className="h-3.5 w-3.5" aria-hidden />
            7 photos uploaded
          </span>
        </div>
        <div className="p-4">
          <p className="text-xs font-semibold tracking-[0.12em] text-gold-600 uppercase">
            Generated by Zouza
          </p>
          <p className="mt-1.5 font-display text-lg leading-snug font-semibold text-navy-950">
            Whitewashed Villa with Pool and Montgó Views, Jávea
          </p>
          <p className="mt-1 text-sm text-navy-500">
            4 bed · 3 bath · 210 m² · Tosalet · €2,400/month
          </p>
          <ul className="mt-4 grid grid-cols-2 gap-2 border-t border-line pt-4 text-xs text-navy-700">
            {generatedTags.map((tag, i) => (
              <motion.li
                key={tag.label}
                className="flex items-center gap-1.5"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.35, delay: 0.55 + i * 0.1 }}
              >
                <tag.icon className="h-3.5 w-3.5 text-navy-400" aria-hidden />
                {tag.label}
              </motion.li>
            ))}
          </ul>
        </div>
      </motion.div>
    </section>
  );
}
