"use client";

import { AnimatePresence, motion } from "framer-motion";
import { Check, Loader2 } from "lucide-react";
import Image from "next/image";
import { useEffect, useState } from "react";

const STAGES = [
  "Uploading photos…",
  "Living room detected",
  "Kitchen detected",
  "Sea view detected",
  "3 bedrooms detected",
  "Generating title…",
  "Writing description…",
  "Estimating market value…",
  "Creating buyer FAQ…",
  "Translating…",
  "Publishing…",
] as const;

const PHOTOS = [
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=500&q=70",
  "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=500&q=70",
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=500&q=70",
];

const RESULT_TITLE = "Whitewashed Villa with Pool and Montgó Views";
const CYCLE_MS = 950;

export function LiveDemo() {
  const [stage, setStage] = useState(0);

  useEffect(() => {
    const id = window.setInterval(() => {
      setStage((s) => (s + 1) % (STAGES.length + 3));
    }, CYCLE_MS);
    return () => window.clearInterval(id);
  }, []);

  const done = stage >= STAGES.length;
  const visibleCount = Math.min(stage + 1, STAGES.length);

  return (
    <div className="grid gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center">
      <div className="grid grid-cols-3 gap-2">
        {PHOTOS.map((src) => (
          <div key={src} className="relative aspect-square overflow-hidden rounded-lg bg-sand">
            <Image src={src} alt="" fill className="object-cover" sizes="150px" />
          </div>
        ))}
      </div>

      <div className="rounded-xl border border-line bg-white p-6">
        <div className="space-y-2">
          {STAGES.slice(0, visibleCount).map((s, i) => {
            const isActive = i === visibleCount - 1 && !done;
            return (
              <motion.div
                key={s}
                initial={{ opacity: 0, x: -8 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.3 }}
                className="flex items-center gap-2.5 text-sm"
              >
                {isActive ? (
                  <Loader2 className="h-4 w-4 shrink-0 animate-spin text-navy-400" aria-hidden />
                ) : (
                  <span className="flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-gold-100 text-gold-700">
                    <Check className="h-3 w-3" aria-hidden />
                  </span>
                )}
                <span className={isActive ? "text-navy-500" : "text-navy-900"}>{s}</span>
              </motion.div>
            );
          })}
        </div>

        <AnimatePresence>
          {done ? (
            <motion.div
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              className="mt-5 border-t border-line pt-5"
            >
              <p className="text-xs font-semibold tracking-[0.12em] text-gold-600 uppercase">
                Generated by Zouza
              </p>
              <p className="mt-1.5 font-display text-lg font-semibold text-navy-950">{RESULT_TITLE}</p>
              <p className="mt-1 text-sm text-navy-500">
                4 bed · 3 bath · 210 m² · Jávea · Ready to publish
              </p>
            </motion.div>
          ) : null}
        </AnimatePresence>
      </div>
    </div>
  );
}
