import type {
  Conversation,
  Listing,
  Message,
  Review,
  ViewingRequest,
} from "@/lib/types";
import { totalMoveIn } from "@/lib/utils";

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=80`;

type Seed = Partial<Listing> &
  Pick<
    Listing,
    | "id"
    | "mode"
    | "title"
    | "slug"
    | "summary"
    | "city"
    | "address_area"
    | "property_type"
    | "bedrooms"
    | "bathrooms"
    | "size_m2"
    | "owner_name"
    | "images"
    | "features"
  >;

function listing(seed: Seed): Listing {
  const base: Listing = {
    owner_id: "mock-owner",
    intent: seed.mode === "rent" ? "rent_out" : "sell",
    description: "",
    country: "Spain",
    latitude: null,
    longitude: null,
    floor: null,
    price_monthly: null,
    price_sale: null,
    utilities_monthly: null,
    deposit: null,
    platform_fee_percent: seed.mode === "rent" ? 2 : null,
    total_move_in_cost: null,
    available_from: null,
    minimum_stay: null,
    maximum_stay: null,
    term: null,
    pets_allowed: false,
    pool: false,
    sea_view: false,
    garage: false,
    furnished: false,
    new_build: false,
    direct_owner: true,
    verified_owner: false,
    verified_property: false,
    last_verified_at: null,
    status: "published",
    owner_rules: null,
    rating: null,
    review_count: 0,
    created_at: "2026-05-20T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    ...seed,
  };
  if (base.mode === "rent" && base.price_monthly) {
    base.total_move_in_cost = totalMoveIn(base);
  }
  return base;
}

export const MOCK_LISTINGS: Listing[] = [
  listing({
    id: "l-valencia-penthouse",
    mode: "rent",
    title: "Light-Filled Penthouse with Sea-Facing Terrace in El Cabanyal",
    slug: "penthouse-el-cabanyal-valencia",
    summary: "Penthouse · 2 bed · 2 bath · 96 m² · El Cabanyal, Valencia · Sea Views · Furnished",
    description:
      "A renovated penthouse two streets from Playa de la Malvarrosa. Open-plan living room flowing onto a 30 m² terrace with sea views, a modern kitchen, and two calm bedrooms. El Cabanyal keeps its fishing-village character while being 15 minutes from the centre by tram.",
    city: "Valencia",
    address_area: "El Cabanyal",
    property_type: "penthouse",
    bedrooms: 2,
    bathrooms: 2,
    size_m2: 96,
    floor: 5,
    price_monthly: 1450,
    utilities_monthly: 140,
    deposit: 1450,
    available_from: "2026-08-01",
    minimum_stay: "6 months",
    term: "long_term",
    sea_view: true,
    furnished: true,
    pets_allowed: true,
    verified_owner: true,
    verified_property: true,
    last_verified_at: "2026-06-20T00:00:00Z",
    owner_name: "Marta G.",
    owner_rules: "No smoking indoors. Quiet hours after 22:00.",
    rating: 4.9,
    review_count: 14,
    images: [
      img("photo-1522708323590-d24dbb6b0267"),
      img("photo-1502672260266-1c1ef2d93688"),
      img("photo-1560448204-e02f11c3d0e2"),
    ],
    features: ["Sea-view terrace", "Fully furnished", "Air conditioning", "Fibre internet", "Lift", "Tram 2 min walk"],
  }),
  listing({
    id: "l-javea-villa",
    mode: "rent",
    title: "Whitewashed Villa with Pool and Montgó Views, Jávea",
    slug: "villa-pool-javea",
    summary: "Villa · 4 bed · 3 bath · 210 m² · Tosalet, Jávea · Pool · Garage · Furnished",
    description:
      "A classic Costa Blanca villa on a quiet residential street in Tosalet. Mature garden, private pool, covered naya for outdoor dining, and views to the Montgó massif. Ten minutes to the Arenal beach and its restaurants.",
    city: "Jávea",
    address_area: "Tosalet",
    property_type: "villa",
    bedrooms: 4,
    bathrooms: 3,
    size_m2: 210,
    price_monthly: 2400,
    utilities_monthly: 220,
    deposit: 2400,
    available_from: "2026-09-01",
    minimum_stay: "12 months",
    term: "long_term",
    pool: true,
    garage: true,
    furnished: true,
    pets_allowed: true,
    verified_owner: true,
    verified_property: true,
    last_verified_at: "2026-06-08T00:00:00Z",
    owner_name: "Familie Brandt",
    owner_rules: "Pets welcome. Garden maintenance included; pool cleaning fortnightly.",
    rating: 4.8,
    review_count: 9,
    images: [
      img("photo-1512917774080-9991f1c4c750"),
      img("photo-1600566753190-17f0baa2a6c3"),
      img("photo-1600607687939-ce8a6c25118c"),
    ],
    features: ["Private pool", "Montgó views", "Covered naya", "Garage + carport", "Outdoor kitchen", "Mature garden"],
  }),
  listing({
    id: "l-palma-apartment",
    mode: "rent",
    title: "Restored Old-Town Apartment with Stone Walls, Palma",
    slug: "old-town-apartment-palma",
    summary: "Apartment · 1 bed · 1 bath · 68 m² · Casco Antiguo, Palma · Furnished",
    description:
      "Original stone walls, high beamed ceilings and a juliet balcony over a pedestrian lane in Palma's old town. Fully renovated with underfloor heating and a quiet interior bedroom. Cafés, the cathedral and the seafront are all on foot.",
    city: "Palma de Mallorca",
    address_area: "Casco Antiguo",
    property_type: "apartment",
    bedrooms: 1,
    bathrooms: 1,
    size_m2: 68,
    floor: 2,
    price_monthly: 1250,
    utilities_monthly: 110,
    deposit: 1250,
    available_from: "2026-07-15",
    minimum_stay: "3 months",
    term: "medium_term",
    furnished: true,
    verified_owner: true,
    verified_property: false,
    last_verified_at: "2026-06-25T00:00:00Z",
    owner_name: "Joan R.",
    rating: 4.7,
    review_count: 6,
    images: [
      img("photo-1560185007-cde436f6a4d0"),
      img("photo-1560185127-6ed189bf02f4"),
      img("photo-1600210492486-724fe5c67fb0"),
    ],
    features: ["Historic building", "Underfloor heating", "Beamed ceilings", "Walk everywhere", "Furnished"],
  }),
  listing({
    id: "l-alicante-flat",
    mode: "rent",
    title: "Bright Two-Bedroom Flat near Playa San Juan, Alicante",
    slug: "flat-playa-san-juan-alicante",
    summary: "Apartment · 2 bed · 1 bath · 82 m² · Playa de San Juan, Alicante · Pool · Garage",
    description:
      "Seventh-floor flat in a well-kept residential complex with communal pool and tennis court, 400 m from the sand of Playa de San Juan. East-facing living room with morning sun, practical kitchen, and a garage space included.",
    city: "Alicante",
    address_area: "Playa de San Juan",
    property_type: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    size_m2: 82,
    floor: 7,
    price_monthly: 1100,
    utilities_monthly: 120,
    deposit: 1100,
    available_from: "2026-07-10",
    minimum_stay: "6 months",
    term: "long_term",
    pool: true,
    garage: true,
    sea_view: true,
    verified_owner: false,
    verified_property: false,
    owner_name: "Carmen L.",
    rating: 4.5,
    review_count: 3,
    images: [
      img("photo-1600121848594-d8644e57abab"),
      img("photo-1584622650111-993a426fbf0a"),
      img("photo-1522708323590-d24dbb6b0267"),
    ],
    features: ["Communal pool", "Tennis court", "Garage space", "400 m to beach", "Tram to centre"],
  }),
  listing({
    id: "l-seville-townhouse",
    mode: "rent",
    title: "Andalusian Townhouse with Patio in Triana, Seville",
    slug: "townhouse-triana-seville",
    summary: "Townhouse · 3 bed · 2 bath · 140 m² · Triana, Seville · Furnished · Pets OK",
    description:
      "A traditional casa de vecinos reborn as a single family home: central patio with orange tree, cool tiled floors, roof terrace with Giralda views. Triana's market, ceramics workshops and river walks at the doorstep.",
    city: "Seville",
    address_area: "Triana",
    property_type: "townhouse",
    bedrooms: 3,
    bathrooms: 2,
    size_m2: 140,
    price_monthly: 1600,
    utilities_monthly: 150,
    deposit: 1600,
    available_from: "2026-08-15",
    minimum_stay: "12 months",
    term: "long_term",
    furnished: true,
    pets_allowed: true,
    verified_owner: true,
    verified_property: true,
    last_verified_at: "2026-06-15T00:00:00Z",
    owner_name: "Álvaro M.",
    owner_rules: "No short-term subletting.",
    rating: 5.0,
    review_count: 11,
    images: [
      img("photo-1600585154340-be6161a56a0c"),
      img("photo-1600566752355-35792bedcfea"),
      img("photo-1560185007-cde436f6a4d0"),
    ],
    features: ["Central patio", "Roof terrace", "Historic quarter", "Furnished", "Pets welcome"],
  }),
  listing({
    id: "l-barcelona-studio",
    mode: "rent",
    title: "Design Studio Steps from Passeig de Gràcia, Barcelona",
    slug: "studio-eixample-barcelona",
    summary: "Studio · 1 bath · 45 m² · Eixample Dret, Barcelona · Furnished",
    description:
      "A carefully designed 45 m² studio in a modernist Eixample building: sleeping alcove, full kitchen, work desk by the gallery window. Metro, Gaudí and the city's best coffee within five minutes on foot.",
    city: "Barcelona",
    address_area: "Eixample Dret",
    property_type: "studio",
    bedrooms: 0,
    bathrooms: 1,
    size_m2: 45,
    floor: 3,
    price_monthly: 1150,
    utilities_monthly: 95,
    deposit: 1150,
    available_from: "2026-07-05",
    minimum_stay: "1 month",
    term: "short_term",
    furnished: true,
    verified_owner: true,
    verified_property: false,
    last_verified_at: "2026-06-22T00:00:00Z",
    owner_name: "Núria P.",
    rating: 4.6,
    review_count: 21,
    images: [
      img("photo-1502672260266-1c1ef2d93688"),
      img("photo-1560448204-e02f11c3d0e2"),
      img("photo-1600210492486-724fe5c67fb0"),
    ],
    features: ["Modernist building", "Work desk + fibre", "Sleeping alcove", "Metro 2 min", "Furnished"],
  }),
  listing({
    id: "l-marbella-villa",
    mode: "buy",
    title: "Contemporary Villa with Infinity Pool, Golden Mile, Marbella",
    slug: "villa-golden-mile-marbella",
    summary: "Villa · 5 bed · 4 bath · 380 m² · Golden Mile, Marbella · Pool · Sea Views · Garage",
    description:
      "Architect-designed villa on Marbella's Golden Mile: double-height living space, infinity pool merging with the sea horizon, five suites, and a three-car garage. Walking distance to the beach clubs and Puente Romano.",
    city: "Marbella",
    address_area: "Golden Mile",
    property_type: "villa",
    bedrooms: 5,
    bathrooms: 4,
    size_m2: 380,
    price_sale: 2950000,
    pool: true,
    sea_view: true,
    garage: true,
    new_build: true,
    verified_owner: true,
    verified_property: true,
    last_verified_at: "2026-06-12T00:00:00Z",
    owner_name: "Golden Mile Estates (owner-direct)",
    rating: 4.9,
    review_count: 5,
    images: [
      img("photo-1613490493576-7fde63acd811"),
      img("photo-1613977257363-707ba9348227"),
      img("photo-1571939228382-b2f2b585ce15"),
    ],
    features: ["Infinity pool", "Sea views", "5 en-suite bedrooms", "3-car garage", "Smart home", "New build"],
  }),
  listing({
    id: "l-denia-apartment",
    mode: "buy",
    title: "Frontline Beach Apartment with Wide Sea Views, Dénia",
    slug: "beach-apartment-denia",
    summary: "Apartment · 3 bed · 2 bath · 110 m² · Les Marines, Dénia · Sea Views · Pool",
    description:
      "First-line apartment on Les Marines beach: 110 m², three bedrooms, a 20 m² terrace directly over the sand, communal pools and gardens. Sold furnished by the original owner — a turn-key holiday home or rental investment.",
    city: "Dénia",
    address_area: "Les Marines",
    property_type: "apartment",
    bedrooms: 3,
    bathrooms: 2,
    size_m2: 110,
    floor: 4,
    price_sale: 385000,
    pool: true,
    sea_view: true,
    furnished: true,
    verified_owner: true,
    verified_property: true,
    last_verified_at: "2026-06-19T00:00:00Z",
    owner_name: "Peter & Anja K.",
    rating: 4.8,
    review_count: 7,
    images: [
      img("photo-1600047509807-ba8f99d2cdde"),
      img("photo-1600566753190-17f0baa2a6c3"),
      img("photo-1584622650111-993a426fbf0a"),
    ],
    features: ["Frontline beach", "20 m² sea terrace", "Sold furnished", "Communal pools", "Storage room"],
  }),
  listing({
    id: "l-granada-carmen",
    mode: "buy",
    title: "Historic Carmen with Alhambra Views, Albaicín, Granada",
    slug: "carmen-albaicin-granada",
    summary: "House · 4 bed · 3 bath · 220 m² · Albaicín, Granada · Garden",
    description:
      "A rare carmen in the UNESCO-listed Albaicín: walled garden with fountain, tiered terraces facing the Alhambra, and 220 m² of restored interiors blending Moorish and Andalusian detail. Direct sale by the family that restored it.",
    city: "Granada",
    address_area: "Albaicín",
    property_type: "house",
    bedrooms: 4,
    bathrooms: 3,
    size_m2: 220,
    price_sale: 890000,
    verified_owner: true,
    verified_property: false,
    last_verified_at: "2026-05-30T00:00:00Z",
    owner_name: "Familia Vega",
    rating: 4.7,
    review_count: 2,
    images: [
      img("photo-1580587771525-78b9dba3b914"),
      img("photo-1600585154340-be6161a56a0c"),
      img("photo-1560185127-6ed189bf02f4"),
    ],
    features: ["Alhambra views", "Walled garden", "UNESCO quarter", "Restored 2019", "Direct owner"],
  }),
  listing({
    id: "l-sitges-townhouse",
    mode: "buy",
    title: "Renovated Townhouse Two Streets from the Sea, Sitges",
    slug: "townhouse-centre-sitges",
    summary: "Townhouse · 3 bed · 2 bath · 165 m² · Centre, Sitges · Roof Terrace",
    description:
      "A 19th-century townhouse fully renovated in 2023: three floors, sea-glimpse roof terrace with outdoor shower, and a patio kitchen made for long lunches. Two streets from Sant Sebastià beach and the train to Barcelona.",
    city: "Sitges",
    address_area: "Centre",
    property_type: "townhouse",
    bedrooms: 3,
    bathrooms: 2,
    size_m2: 165,
    price_sale: 1150000,
    verified_owner: true,
    verified_property: true,
    last_verified_at: "2026-06-24T00:00:00Z",
    owner_name: "Laia & Marc",
    new_build: false,
    rating: 4.9,
    review_count: 4,
    images: [
      img("photo-1600596542815-ffad4c1539a9"),
      img("photo-1600607687939-ce8a6c25118c"),
      img("photo-1600566752355-35792bedcfea"),
    ],
    features: ["Renovated 2023", "Roof terrace", "Patio kitchen", "2 min to beach", "Train to BCN 35 min"],
  }),
  listing({
    id: "l-mallorca-finca",
    mode: "buy",
    title: "Stone Finca with Olive Grove and Pool near Sóller, Mallorca",
    slug: "finca-soller-mallorca",
    summary: "Finca · 4 bed · 3 bath · 260 m² · Sóller Valley, Mallorca · Pool · Garage",
    description:
      "A restored stone finca in the Sóller valley: 12,000 m² of olive and orange trees, mountain-view pool, original pressed-tile floors and a modern kitchen in the old mill room. Serious buyers only — a once-a-decade property.",
    city: "Sóller",
    address_area: "Sóller Valley",
    property_type: "finca",
    bedrooms: 4,
    bathrooms: 3,
    size_m2: 260,
    price_sale: 1950000,
    pool: true,
    garage: true,
    verified_owner: true,
    verified_property: true,
    last_verified_at: "2026-06-02T00:00:00Z",
    owner_name: "Miquel A.",
    rating: 5.0,
    review_count: 3,
    images: [
      img("photo-1523217582562-09d0def993a6"),
      img("photo-1512917774080-9991f1c4c750"),
      img("photo-1580587771525-78b9dba3b914"),
    ],
    features: ["12,000 m² land", "Olive & orange grove", "Mountain-view pool", "Original tiles", "Guest annex"],
  }),
  listing({
    id: "l-malaga-penthouse",
    mode: "buy",
    title: "New-Build Penthouse over the Port, Málaga Centro",
    slug: "penthouse-soho-malaga",
    summary: "Penthouse · 3 bed · 2 bath · 128 m² · Soho, Málaga · Sea Views · Garage · New Build",
    description:
      "Top-floor penthouse in a 2025 development in Málaga's Soho arts district: 40 m² wraparound terrace over the port, floor-to-ceiling glazing, two garage spaces. Delivered new, direct from the owner-developer.",
    city: "Málaga",
    address_area: "Soho",
    property_type: "penthouse",
    bedrooms: 3,
    bathrooms: 2,
    size_m2: 128,
    floor: 9,
    price_sale: 780000,
    sea_view: true,
    garage: true,
    new_build: true,
    verified_owner: true,
    verified_property: true,
    last_verified_at: "2026-06-26T00:00:00Z",
    owner_name: "Puerto Soho SL (owner-direct)",
    rating: 4.6,
    review_count: 2,
    images: [
      img("photo-1560448204-e02f11c3d0e2"),
      img("photo-1502672260266-1c1ef2d93688"),
      img("photo-1600121848594-d8644e57abab"),
    ],
    features: ["40 m² terrace", "Port & sea views", "2 garage spaces", "Delivered 2025", "Arts district"],
  }),
];

export function getMockListing(idOrSlug: string): Listing | undefined {
  return MOCK_LISTINGS.find((l) => l.id === idOrSlug || l.slug === idOrSlug);
}

/* ------------------------------------------------------------------ */
/* Reviews                                                             */
/* ------------------------------------------------------------------ */

export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    listing_id: "l-valencia-penthouse",
    author_name: "Sofia",
    rating: 5,
    comment:
      "The listing matched reality exactly — photos, costs, everything. The AI assistant answered my questions at midnight and the owner confirmed a viewing the next morning.",
    created_at: "2026-05-28T00:00:00Z",
  },
  {
    id: "r2",
    listing_id: "l-valencia-penthouse",
    author_name: "Jonas",
    rating: 5,
    comment:
      "Total move-in cost was shown upfront. No surprises at contract time, which has never happened to me before in Spain.",
    created_at: "2026-04-14T00:00:00Z",
  },
  {
    id: "r3",
    listing_id: "l-javea-villa",
    author_name: "Helen",
    rating: 5,
    comment:
      "Verified owner, video walkthrough before we flew out, and the deposit terms were written down clearly. This is how renting should work.",
    created_at: "2026-05-02T00:00:00Z",
  },
  {
    id: "r4",
    listing_id: "l-marbella-villa",
    author_name: "Richard",
    rating: 5,
    comment:
      "Dealt with the owner directly. The AI exposé was more complete than most agency brochures I have paid for.",
    created_at: "2026-05-19T00:00:00Z",
  },
];

export function getMockReviews(listingId: string): Review[] {
  return MOCK_REVIEWS.filter((r) => r.listing_id === listingId);
}

/* ------------------------------------------------------------------ */
/* Conversations & messages                                            */
/* ------------------------------------------------------------------ */

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "c1",
    listing_id: "l-valencia-penthouse",
    listing_title: "Light-Filled Penthouse with Sea-Facing Terrace",
    listing_image: img("photo-1522708323590-d24dbb6b0267"),
    counterpart_name: "Marta G. (owner)",
    counterpart_role: "owner",
    last_message_at: "2026-07-01T18:42:00Z",
    unread: 1,
    prequalified: true,
    prequalification_note: "Budget confirmed · Move-in Aug · 1 small dog",
  },
  {
    id: "c2",
    listing_id: "l-javea-villa",
    listing_title: "Whitewashed Villa with Pool and Montgó Views",
    listing_image: img("photo-1512917774080-9991f1c4c750"),
    counterpart_name: "Familie Brandt (owner)",
    counterpart_role: "owner",
    last_message_at: "2026-06-30T10:05:00Z",
    unread: 0,
    prequalified: true,
    prequalification_note: "12-month stay · Family of 4 · References ready",
  },
  {
    id: "c3",
    listing_id: "l-denia-apartment",
    listing_title: "Frontline Beach Apartment with Wide Sea Views",
    listing_image: img("photo-1600047509807-ba8f99d2cdde"),
    counterpart_name: "Peter & Anja K. (owners)",
    counterpart_role: "owner",
    last_message_at: "2026-06-27T16:20:00Z",
    unread: 0,
    prequalified: false,
    prequalification_note: null,
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: "m1",
    conversation_id: "c1",
    sender: "me",
    body: "Hola Marta! Is the penthouse available from 1 August? We are two people with a small, quiet dog.",
    created_at: "2026-07-01T17:55:00Z",
  },
  {
    id: "m2",
    conversation_id: "c1",
    sender: "zouza_ai",
    body: "Zouza pre-check: this enquiry matches the listing — availability from 1 Aug ✓, pets allowed ✓, budget confirmed ✓. Passed to the owner as a qualified lead.",
    created_at: "2026-07-01T17:55:30Z",
  },
  {
    id: "m3",
    conversation_id: "c1",
    sender: "them",
    body: "Hi! Yes, 1 August works. Dogs are welcome. Would you like a video viewing this week, or in person on Saturday morning?",
    created_at: "2026-07-01T18:42:00Z",
  },
  {
    id: "m4",
    conversation_id: "c2",
    sender: "me",
    body: "Good morning — we are a family of four relocating to Jávea in September. Is a 12-month contract possible, and is the garden maintained?",
    created_at: "2026-06-30T09:30:00Z",
  },
  {
    id: "m5",
    conversation_id: "c2",
    sender: "them",
    body: "Welcome! Yes, 12 months is exactly what we prefer. Garden and pool maintenance are included in the rent. Happy to arrange a viewing.",
    created_at: "2026-06-30T10:05:00Z",
  },
  {
    id: "m6",
    conversation_id: "c3",
    sender: "me",
    body: "Hello — is the Dénia apartment still for sale? Could you share the community fees and the IBI?",
    created_at: "2026-06-27T15:48:00Z",
  },
  {
    id: "m7",
    conversation_id: "c3",
    sender: "them",
    body: "Yes, still available. Community fees are 145 €/month including the pools; IBI was 620 € last year. Documents are in the listing's contract area.",
    created_at: "2026-06-27T16:20:00Z",
  },
];

/* ------------------------------------------------------------------ */
/* Viewing requests (owner dashboard)                                  */
/* ------------------------------------------------------------------ */

export const MOCK_VIEWING_REQUESTS: ViewingRequest[] = [
  {
    id: "v1",
    listing_id: "l-valencia-penthouse",
    listing_title: "Penthouse, El Cabanyal",
    requester_name: "Sofia N.",
    preferred_date: "2026-07-05",
    status: "pending",
    note: "Saturday morning if possible — flying in Friday night.",
    created_at: "2026-07-01T18:50:00Z",
  },
  {
    id: "v2",
    listing_id: "l-valencia-penthouse",
    listing_title: "Penthouse, El Cabanyal",
    requester_name: "Daniel & Ana",
    preferred_date: "2026-07-08",
    status: "confirmed",
    note: null,
    created_at: "2026-06-29T12:10:00Z",
  },
  {
    id: "v3",
    listing_id: "l-javea-villa",
    listing_title: "Villa, Tosalet",
    requester_name: "The Brandt family",
    preferred_date: "2026-07-12",
    status: "pending",
    note: "Video call first would be great.",
    created_at: "2026-06-30T10:15:00Z",
  },
];

export const SPAIN_DESTINATIONS = [
  { name: "Valencia", tagline: "City + beach living", image: img("photo-1560448204-e02f11c3d0e2"), count: 214 },
  { name: "Costa Blanca", tagline: "Jávea · Dénia · Altea", image: img("photo-1512917774080-9991f1c4c750"), count: 342 },
  { name: "Mallorca", tagline: "Palma & the Tramuntana", image: img("photo-1523217582562-09d0def993a6"), count: 189 },
  { name: "Costa del Sol", tagline: "Marbella · Málaga", image: img("photo-1613490493576-7fde63acd811"), count: 276 },
  { name: "Barcelona", tagline: "Eixample to Sitges", image: img("photo-1502672260266-1c1ef2d93688"), count: 158 },
  { name: "Andalusia", tagline: "Seville · Granada", image: img("photo-1580587771525-78b9dba3b914"), count: 131 },
];
